apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
data:
  spring.profiles.active: test
  eureka.client.serviceUrl.defaultZone: http://eureka-service:8761/eureka/
  spring.datasource.url: jdbc:mysql://kubernetes.docker.internal:3306/test

