version: '3.7'

services:
  eureka:
    build: ./eureka
    image: mwz/eureka
    environment:
      - spring.profiles.active
    ports:
      - 8761:8761
    networks:
      - internal_access
      - external_access

  gateway:
      build: ./gateway
      image: mwz/gateway
      environment:
        - spring.profiles.active
        - eureka.client.serviceUrl.defaultZone
      depends_on:
        - eureka
      ports:
        - 80:80
      networks:
        - internal_access
        - external_access

  service-v1:
    build: ./service-v1
    image: mwz/service-v1
    environment:
      - spring.profiles.active
      - spring.datasource.url
      - eureka.client.serviceUrl.defaultZone
    depends_on:
      - eureka
    networks:
      - internal_access
      - external_access

  service-v2:
      build: ./service-v2
      image: mwz/service-v2
      environment:
        - spring.profiles.active
        - eureka.client.serviceUrl.defaultZone
      depends_on:
        - eureka
      networks:
        - internal_access

networks:
  internal_access:
    internal: true
  external_access: