apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eureka-svc-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka-svc
        env: test
    spec:
      containers:
        - name: eureka-svc
          image: mwz/eureka
          imagePullPolicy: Never
          ports:
            - name: http-port
              containerPort: 8761

---
apiVersion: v1
kind: Service
metadata:
  name: eureka-service
spec:
  selector:
    app: eureka-svc
    env: test
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761