apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gateway-svc-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway-svc
        env: test
    spec:
      containers:
        - name: gateway-svc
          image: mwz/gateway
          imagePullPolicy: Never
          ports:
            - name: http-port
              containerPort: 80
          envFrom:
            - configMapRef:
                name: common-config
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway-svc
    env: test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
  type: NodePort